/**
 * Encore API client configuration
 * 
 * Why this exists:
 * - Provides configured instance of auto-generated Encore TypeScript client
 * - Manages base URL from environment variables
 * - Handles authentication token injection
 * - Type-safe API calls across the frontend
 */

// This will be imported once encore-client.ts is generated
// import { Client } from './encore-client';

/**
 * Configured Encore API client instance
 * Usage: import { api } from '$api/client';
 * 
 * NOTE: encore-client.ts will be generated by running:
 * encore gen client typescript --output=frontend/src/lib/api/encore-client.ts
 * 
 * Or use: task gen:client
 */
export const api = null as any; // Will be replaced after client generation

// Placeholder type for development
export type APIClient = any;

